version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - ./api/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  front:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
  api:
    build: ./api
    command: bash -c "rm -f api/tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - ./api:/myapp
    ports:
      - "4000:4000"
    depends_on:
      - db